spring:
  ##datasource:
  ## initialization-mode: embedded
  ## url: jdbc:h2:file:/data/demo
  ## username: sa
  ## password: password
  ## driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql.init.mode: always

  h2:
    console.enabled: true
